repos:
  - repo: https://github.com/johnnymorganz/stylua
    rev: v0.13.1
    hooks:
      - id: stylua-github
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        exclude: "^test/"
